### ISSUE TITLE
Had an issue with unicode characters

### ISSUE THREAD

**Issue by yuval-a** [sters/php-regexp-trie#1]
e.g. with this string: "`german revolution of 1918–19`"
The hyphen between the numbers is an "em dash" - it's a 3 bytes unicode char,
the char iteration loop (inside the `add` function) resulted with "german revolution of 1918" added and not the whole string.
I changed the code, based on [this stackoverflow answer](https://stackoverflow.com/a/14366023/522169):

```
        for ($i = 0, $m = strlen($str); $i < $m; $i++) {
            $char = $str[$i];
            $ord = ord($char);
            if($ord > 127) {
                switch (true) {
                    case ($ord < 224):  $bytes=2; break;
                    case ($ord < 240):  $bytes=3; break;
                    case ($ord < 248):  $bytes=4; break;
                    case ($ord == 252): $bytes=5; break;
                    default: $bytes = 6; break;
                }
                $char = substr($str, $i, $bytes);
                $i += $bytes-1;
            }

       ...

```

Notice I had to change `mb_strlen` to regular `strlen` for this to work correctly

**Comment by sters** [comment]
Thanks report issue! I will check this.

**Comment by sters** [comment]
Since the code of Stackoverflow taught me was good, I made it as it was method.
Also added a corresponding test case, how about with this

**Comment by sters** [comment]
I was merge and new release that!
